// productDB.js
const allProducts = [
  {
    id: 1,
    brand: "Dell",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 899.99,
    category: "laptop",
  },
  {
    id: 2,
    brand: "HP",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1099.99,
    category: "laptop",
  },
  {
    id: 3,
    brand: "Lenovo",
    RAM: "12GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 799.99,
    category: "laptop",
  },
  {
    id: 4,
    brand: "Acer",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 749.99,
    category: "laptop",
  },
  {
    id: 5,
    brand: "Asus",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 999.99,
    category: "laptop",
  },
  {
    id: 6,
    brand: "Apple",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1299.99,
    category: "laptop",
  },
  {
    id: 7,
    brand: "Microsoft",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 899.99,
    category: "laptop",
  },
  {
    id: 8,
    brand: "Samsung",
    RAM: "12GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1099.99,
    category: "laptop",
  },
  {
    id: 9,
    brand: "Toshiba",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 799.99,
    category: "laptop",
  },
  {
    id: 10,
    brand: "Sony",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 999.99,
    category: "laptop",
  },
  {
    id: 11,
    brand: "LG",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 899.99,
    category: "laptop",
  },
  {
    id: 12,
    brand: "Gateway",
    RAM: "12GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1099.99,
    category: "laptop",
  },
  {
    id: 13,
    brand: "MSI",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1299.99,
    category: "laptop",
  },
  {
    id: 14,
    brand: "Fujitsu",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 799.99,
    category: "laptop",
  },
  {
    id: 15,
    brand: "Panasonic",
    RAM: "12GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1099.99,
    category: "laptop",
  },
  {
    id: 16,
    brand: "Google",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 999.99,
    category: "laptop",
  },
  {
    id: 17,
    brand: "Razer",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 899.99,
    category: "laptop",
  },
  {
    id: 18,
    brand: "Acer",
    RAM: "16GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1299.99,
    category: "laptop",
  },
  {
    id: 19,
    brand: "Huawei",
    RAM: "12GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 1099.99,
    category: "laptop",
  },
  {
    id: 20,
    brand: "Xiaomi",
    RAM: "8GB",
    imgurl: "https://m.media-amazon.com/images/I/61Qe0euJJZL.jpg",
    price: 799.99,
    category: "laptop",
  },
  // desktops
  {
    id: 21,
    brand: "Dell",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 899.99,
    category: "desktop",
  },
  {
    id: 22,
    brand: "HP",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1099.99,
    category: "desktop",
  },
  {
    id: 23,
    brand: "Lenovo",
    RAM: "12GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 799.99,
    category: "desktop",
  },
  {
    id: 24,
    brand: "Acer",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 749.99,
    category: "desktop",
  },
  {
    id: 25,
    brand: "Asus",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 999.99,
    category: "desktop",
  },
  {
    id: 26,
    brand: "Apple",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1299.99,
    category: "desktop",
  },
  {
    id: 27,
    brand: "Microsoft",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 899.99,
    category: "desktop",
  },
  {
    id: 28,
    brand: "Samsung",
    RAM: "12GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1099.99,
    category: "desktop",
  },
  {
    id: 29,
    brand: "Toshiba",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 799.99,
    category: "desktop",
  },
  {
    id: 30,
    brand: "Sony",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 999.99,
    category: "desktop",
  },
  {
    id: 31,
    brand: "LG",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 899.99,
    category: "desktop",
  },
  {
    id: 32,
    brand: "Gateway",
    RAM: "12GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1099.99,
    category: "desktop",
  },
  {
    id: 33,
    brand: "MSI",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1299.99,
    category: "desktop",
  },
  {
    id: 34,
    brand: "Fujitsu",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 799.99,
    category: "desktop",
  },
  {
    id: 35,
    brand: "Panasonic",
    RAM: "12GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1099.99,
    category: "desktop",
  },
  {
    id: 36,
    brand: "Google",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 999.99,
    category: "desktop",
  },
  {
    id: 37,
    brand: "Razer",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 899.99,
    category: "desktop",
  },
  {
    id: 38,
    brand: "Acer",
    RAM: "16GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1299.99,
    category: "desktop",
  },
  {
    id: 39,
    brand: "Huawei",
    RAM: "12GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 1099.99,
    category: "desktop",
  },
  {
    id: 40,
    brand: "Xiaomi",
    RAM: "8GB",
    imgurl:
      "https://retentionrange.co.bw/computers/desktops/pc-pics/retention-desktop.png",
    price: 799.99,
    category: "desktop",
  },
];

export default allProducts;
